apiVersion: v1
kind: Service
metadata:
  name: sentiment-service
  labels:
    app: sentiment-model # This matches the label in Deployment
spec:
  selector:
    app: sentiment-model
  ports:
  - name: http-metrics  # Name used by ServiceMonitor
    protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP